export const data = [
  { id: 1, country: "O'zbekiston", region: "Osiyo", city: "Toshkent", zipCode: "12345", rooms: "3", size: "50 m2", sort: "yaxshi", minPrice: "300$", maxPrice: "500$" },
  { id: 2, country: "Rassiya", region: "Osiyo", city: "Maskva", zipCode: "23456", rooms: "2", size: "30 m2", sort: " yaxshi", minPrice: "250$", maxPrice: "300$" },
  { id: 3, country: "Xitoy", region: "Osiyo", city: "Pekin", zipCode: "34567", rooms: "4", size: "70 m2", sort: "a'lo", minPrice: "300$", maxPrice: "700$" },
  { id: 4, country: "Amerika Qo'shma Shtatlari", region: "Amerika", city: "Vashngton", zipCode: "45678", rooms: "3", size: "55 m2", sort: "yaxshi", minPrice: "200$", maxPrice: "350$" },
  { id: 5, country: "Buyuk Britaniya", region: "Okeaniya va Evropa", city: "London", zipCode: "56789", rooms: "2", size: "30 m2", sort: "yaxshi", minPrice: "200$", maxPrice: "250$" },
  { id: 6, country: "O'zbekiston", region: "Osiyo", city: "Toshkent", zipCode: "67890", rooms: "1", size: "20 m2", sort: "o'rtacha", minPrice: "200$", maxPrice: "200$" },
  { id: 7, country: "Yaponiya", region: "Osiyo", city: "Tokio", zipCode: "78901", rooms: "3", size: "50 m2", sort: "a'lo", minPrice: "400$", maxPrice: "800$" },
  { id: 8, country: "Korea", region: "Osiyo", city: "Seul", zipCode: "89012", rooms: "4", size: "70 m2", sort: "a'lo", minPrice: "500$", maxPrice: "1000$" },
  { id: 9, country: "BAA", region: "Afrika", city: "Abu Dabi", zipCode: "90123", rooms: "5", size: "100 m2", sort: "a'lo", minPrice: "600$", maxPrice: "1200$" },
  { id: 10, country: "Saudiya Arabistoni", region: "Osiyo", city: "Al Riyod", zipCode: "10293", rooms: "4", size: "80 m2", sort: "yaxshi", minPrice: "500$", maxPrice: "800$" },
  { id: 11, country: "Yangi Zellandiya", region: "Okeaniya va Evropa", city: "Vellington", zipCode: "29384", rooms: "3", size: "50 m2", sort: "yaxshi", minPrice: "300$", maxPrice: "700$" },
  { id: 12, country: "Turkiya", region: "Osiyo", city: "Anqara", zipCode: "47563", rooms: "2", size: "40 m2", sort: "", minPrice: "300$", maxPrice: "400$" },
  { id: 13, country: "Qozog'iston", region: "Osiyo", city: "Ostona", zipCode: "52056", rooms: "2", size: "45 m2", sort: "o'rtacha", minPrice: "200$", maxPrice: "300$" },
  { id: 14, country: "Qizg'iziston", region: "Osiyo", city: "Bishkek", zipCode: "92578", rooms: "3", size: "55 m2", sort: "yaxshi", minPrice: "300$", maxPrice: "500$" },
  { id: 15, country: "Tojikiston", region: "Osiyo", city: "Dushanbe", zipCode: "02578", rooms: "4", size: "60 m2", sort: "yaxshi", minPrice: "500$", maxPrice: "800$" },
  { id: 16, country: "Turkmaniston", region: "Osiyo", city: "Ashhobod", zipCode: "34759", rooms: "4", size: "65 m2", sort: "yaxshi", minPrice: "500$", maxPrice: "600$" },
  { id: 17, country: "O'zbekiston", region: "Osiyo", city: "Toshkent", zipCode: "15813", rooms: "3", size: "40 m2", sort: " yaxshi", minPrice: "300$", maxPrice: "350$" },
  { id: 18, country: "Rassiya", region: "Osiyo", city: "Maskva", zipCode: "58265", rooms: "1", size: "20 m2", sort: "o'rtacha", minPrice: "200$", maxPrice: "250$" },
  { id: 19, country: "Polsha", region: "Okeaniya va Evropa", city: "Varshava", zipCode: "68346", rooms: "3", size: "50 m2", sort: "yaxshi", minPrice: "300$", maxPrice: "600$" },
  { id: 20, country: "Hindiston", region: "Afrika", city: "Dehli", zipCode: "93753", rooms: "2", size: "35 m2", sort: "o'rtacha", minPrice: "300$", maxPrice: "350$" },
]